# Generated by Django 5.0.4 on 2024-05-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=100),
        ),
    ]
