# Generated by Django 5.0.4 on 2024-05-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eName', models.CharField(max_length=25)),
                ('eAge', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
