# Generated by Django 5.0.4 on 2024-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
