# Generated by Django 5.0.4 on 2024-05-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=6788),
            preserve_default=False,
        ),
    ]
