# Generated by Django 5.0.4 on 2024-05-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterForm',
            new_name='RegisterFormModel',
        ),
    ]
